// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"time"
)

type Balance struct {
	Address    string `json:"address"`
	EthBalance string `json:"ethBalance"`
}

type Query struct {
}

type TokenPrice struct {
	ID  string  `json:"id"`
	Usd float64 `json:"usd"`
}

type Transaction struct {
	Hash      string    `json:"hash"`
	From      string    `json:"from"`
	To        string    `json:"to"`
	Value     string    `json:"value"`
	TimeStamp time.Time `json:"timeStamp"`
}
